### PR TITLE
addying dynamic battery icon for polybar

### PR DESCRIPTION
**Pull request by alphaprads**
adding a ramp and animation to battery icon to better show status of battery previously this was empty but now it is filled according to amount of battery

### CODE REVIEW

**Comment by alphaprads** [comment]
if anything is wrong /any changes you think in this please tell me i'll work on it / any changes or reasons

**Comment by alphaprads** [comment]
if you think this is wrong / any changes are required tell me i'll work on it

**Comment by Keyitdev** [comment]
I tried it out, it's a pretty good config. I don't want to sound mean, but I won't merge it due to the fact that polybar uses a special icon set called feather 
https://at-ui.github.io/feather-font/ 
https://github.com/AT-UI/feather-font. 

And I want to be consistent. Every icon used in this dotfiles comes from this set. 

I think it is a cool idea, you can keep it on your own fork. Besides that I am having one problem. When I loaded your config it looks like this. 

image

**Comment by alphaprads** [comment]
Oh i can patch that very sorry left a space there 

i can understand don't worry 


I'm happy that you think it is a cool idea 


If there's anything you want me to do just hit me up and i can help you in this project in any way possible


I really appreciate the work you put in these config file

**Comment by alphaprads** [comment]
i've updated the project now it's working in case you change your mind you can just copy it from here.

**Pull request closed without merging**
